language: objective-c
osx_image: xcode10.2
xcode_workspace: Iguazu.xcworkspace
xcode_scheme: IguazuTests
script: xcodebuild -scheme IguazuTests -sdk iphonesimulator12.2 -destination 'platform=iOS Simulator,name=iPhone 6,OS=12.2' clean  test
after_success:
  - bash <(curl -s https://codecov.io/bash)
